server:
  port: 8081
spring:
  r2dbc:
    url: ${USER_R2DBC_URL:r2dbc:postgresql://localhost:5433/users}
    username: ${USER_DB_USERNAME:user_app}
    password: ${USER_DB_PASSWORD:user_local_password}
    pool:
      max-size: 10
  flyway:
    url: ${USER_JDBC_URL:jdbc:postgresql://localhost:5433/users}
    user: ${USER_DB_USERNAME:user_app}
    password: ${USER_DB_PASSWORD:user_local_password}
