CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL CHECK (length(trim(full_name)) > 0),
    email VARCHAR(254) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('STUDENT', 'PROFESSOR', 'ADMIN')),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE study_program (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9_-]+$'),
    name VARCHAR(200) NOT NULL CHECK (length(trim(name)) > 0),
    description VARCHAR(4000) NOT NULL DEFAULT '',
    archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT NOT NULL REFERENCES app_user(id),
    title VARCHAR(200) NOT NULL CHECK (length(trim(title)) > 0),
    description VARCHAR(4000) NOT NULL DEFAULT '',
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN
        ('DRAFT', 'ENROLLMENT_OPEN', 'ENROLLMENT_CLOSED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT course_dates_valid CHECK (end_date >= start_date)
);

CREATE TABLE course_program (
    course_id BIGINT NOT NULL REFERENCES course(id) ON DELETE CASCADE,
    program_id BIGINT NOT NULL REFERENCES study_program(id),
    PRIMARY KEY (course_id, program_id)
);

CREATE TABLE enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES app_user(id),
    course_id BIGINT NOT NULL REFERENCES course(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENROLLED', 'DROPPED', 'COMPLETED', 'CANCELLED')),
    grade INTEGER CHECK (grade BETWEEN 0 AND 100),
    enrolled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT enrollment_student_course_unique UNIQUE (student_id, course_id),
    CONSTRAINT completed_enrollment_has_grade CHECK (status <> 'COMPLETED' OR grade IS NOT NULL)
);

CREATE INDEX course_professor_idx ON course(professor_id);
CREATE INDEX course_status_id_idx ON course(status, id);
CREATE INDEX course_program_program_idx ON course_program(program_id, course_id);
CREATE INDEX enrollment_course_status_idx ON enrollment(course_id, status);
